# Generated by Django 3.0.4 on 2020-03-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_app', '0002_auto_20200320_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
