# Generated by Django 3.0.4 on 2020-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_app', '0006_auto_20200320_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.URLField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=5000),
        ),
    ]
