# Generated by Django 3.0.4 on 2020-03-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_app', '0011_auto_20200320_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='local_image_url',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
