# Generated by Django 3.0.4 on 2020-03-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_app', '0013_auto_20200323_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='test',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='test',
        ),
    ]
