version: "3.7"
services:
#  riders_db:
#    build: data/riders_db
#    container_name: riders_db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: riders123
#      PG_DATA: /var/lib/postgresql/data
#    volumes:
#      - ./data/riders_db/.data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
  web_scraper_db:
    build: data/web_scraper_db
    container_name: web_scraper_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: travelers123
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./data/web_scraper_db/.data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
#  riders:
#    build: riders
#    container_name: riders
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8001:8000"
#    volumes:
#      - ./riders:/code
#    links:
#      - riders_db
#    environment:
#      DB_HOST: 'riders_db'
#      DB_PORT: 5432
#      DB_USER: plan_it
#      DB_PASSWORD: riders123
#      DB_NAME: riders_db
  travelers_backend:
    build: web_scraper/backend
    container_name: travelers_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"
    volumes:
      - ./web_scraper/backend:/code
    links:
      - web_scraper_db
    environment:
      DB_HOST: 'web_scraper_db'
      DB_PORT: 5432
      DB_USER: plan_it
      DB_PASSWORD: travelers123
      DB_NAME: web_scraper_db
